# Generated by Django 4.2.13 on 2026-06-02 01:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='companies.company')),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessment')),
            ],
            options={
                'db_table': 'assessment_responses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_threshold', models.FloatField(default=6.0, help_text='Flag this program when avg score falls below this value.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_values', models.ManyToManyField(related_name='training_programs', to='companies.companyvalue')),
            ],
            options={
                'db_table': 'training_programs',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ValueRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('company_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='companies.companyvalue')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='assessments.assessmentresponse')),
            ],
            options={
                'db_table': 'value_ratings',
                'unique_together': {('response', 'company_value')},
            },
        ),
    ]
